org: testcompany
app: weather-rest-api-app
service: weather-rest-api-app

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: weather
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: weather/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: weather
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: weather/{id}
          method: get

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: weather/{id}
          method: delete
  openWeather:
    handler: app/handler.openWeather
    events:
      - http:
          path: openweather/{location}
          method: get          
