version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:  
build-and-deploy:
  docker:
    - image: circle/node:10.16.3
  steps:
  - checkout
  - run: 
      command: sudo npm i -g serverless@latest
  - run:
      command: npm install 
  - run:
      command: ./.circleci/install-credentials.sh 
  - run:
      command: sls deploy

workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
            context: serverlessRestAPI
            filter:
                branches:
                    only:
                        - master

